### ISSUE TITLE
Jupyter notebook 4.3.1 breaks kernel creation

### ISSUE THREAD

**Issue by bpburns** [EclairJS/eclairjs#14]
We get an API error when trying to create a new kernel.  It may be CORS related

**Comment by doronrosenberg** [comment]
You can now set either JUPYTER_TOKEN with the token that Jupyter prints out or just do 
`export JUPYTER_URL=http://localhost:8888/?token=a5a1f65075f2c862dfbcaf3b0dfe088b43622ffa8c588da6` and we will parse this out.

We also need to document this as well
