### ISSUE TITLE
Not able to stream kafka producer data.

### ISSUE THREAD

**Issue by ShrinathGupta** [EclairJS/eclairjs#21]
I'm new in eclairjs. 
I want the spark to communicate Kafka consumer and steam the messages that are produced by Kafka producer.
EclairJS Version: 0.10
Docker Image Version : 0.10
Docker Image : eclairjs/minimal-gateway:0.10
**Code snippet** 
```
`var eclairjs = require('eclairjs');

 var spark = new eclairjs();

 var KafkaUtils = require('eclairjs-kafka');
 var kafkaUtils = new KafkaUtils({
    eclairjs: spark
 });
spark.addModule(kafkaUtils);

var session = spark.sql.SparkSession.builder()
        .appName("Demo App")
        .getOrCreate();

var ssc = new spark.streaming.StreamingContext(
    session.sparkContext(),
    new spark.streaming.Duration(250)
);
var kafkaHost = 'x.x.x.x:9092',
    topic = 'ABC';
var messages = kafkaUtils.createStream(ssc, "foo", kafkaHost, topic);

console.log("messages: ", messages); // First time it display ,  DStream {  kernelP: Promise { <pending> },
                                                             //   refIdP: Promise { <pending> } }`
```
But I'm not getting anything to stream data in spark whereas Kafka producer creating messages continuously.
No update on Spark screen. It's only showing:
 **Starting websocket ws://127.0.0.1:8888/api/kernels/b5bf2491-c5ad-4971-a5a7-e2de98c524c1**
Any idea why this weird behaviour.
Am I doing something wrong?

**Comment by QuantumRich** [comment]
I'm having a similar issue.  By chance are you on a proxy?
